roles:
  - src: "git+https://github.com/eclipse-slm/molecule_kubevirt"
    scm: git
    version: main
    name: fabos.molecule_kubevirt

  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-docker"
    scm: git
    version: main
    name: fabos.slm-ansible-role-docker
