---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: wazuh-backend
  gather_facts: true
  become: true
  vars:
    fabos_wazuh_service: backend
    fabos_wazuh_service_state: present
    fabos_wazuh_default_compose_ports:
      - container_port: 5601
        exposed_port: 5443
  tasks:
    - name: Include wazuh role
      ansible.builtin.include_role:
        name: wazuh
