---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true # Disable if your role does not rely on facts
  become: true
  vars:
    fabos_wazuh_service: agent
    fabos_wazuh_service_state: present
  tasks:
    - name: Apply role under test
      ansible.builtin.include_role:
        name: wazuh
