---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge - Backend
  hosts: wazuh-backend
  gather_facts: true
  become: true
  vars:
    fabos_wazuh_service: backend
    fabos_wazuh_service_state: present
  tasks:
    - name: Include wazuh role
      ansible.builtin.include_role:
        name: wazuh

- name: Converge - Agent
  hosts: wazuh-agent
  gather_facts: true
  become: true
  vars:
    fabos_wazuh_service: agent
    fabos_wazuh_service_state: present
    fabos_wazuh_manager_ip: "{{ hostvars[groups['wazuh-backend'][0]].ansible_host }}"
  tasks:
    - name: Include wazuh role
      ansible.builtin.include_role:
        name: wazuh
