---
# tasks file for installing wazuh backend on docker
- name: Set vm.max_map_count sysctl parameter
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_file: /etc/sysctl.d/99-wazuh.conf
    state: present
    reload: true

- name: Compute final Wazuh version for compose URL
  ansible.builtin.set_fact:
    fabos_wazuh_final_version: "{{ fabos_wazuh_backend_version | default(fabos_wazuh_default_version) }}"

- name: Clone Wazuh Docker repository
  ansible.builtin.git:
    repo: "{{ fabos_wazuh_default_wazuh_docker_git_url }}"
    dest: "{{ fabos_wazuh_default_wazuh_docker_dir }}"
    version: "{{ fabos_wazuh_final_version }}"
  register: cloned_repo
  ignore_errors: true

- name: Replace exposed ports in docker-compose file
  ansible.builtin.lineinfile:
    path: "{{ fabos_wazuh_default_single_node_compose_dir }}/docker-compose.yml"
    regexp: '(\s+-\s)"*.*:{{ item.container_port }}"*'
    line: '\g<1>{{ item.exposed_port }}:{{ item.container_port }}'
    backrefs: true
  loop: "{{ fabos_wazuh_default_compose_ports | default([]) }}"

- name: Run docker compose workloads
  community.docker.docker_compose_v2:
    project_src: "{{ fabos_wazuh_default_single_node_compose_dir }}"
    files: "{{ [item] }}"
    state: present
  register: compose_result
  changed_when:
    - compose_result is changed
    - '"Found orphan containers" not in compose_result.stderr'
  loop: "{{ fabos_wazuh_default_compose_files }}"
    # - [generate-indexer-certs.yml]
    # - [docker-compose.yml]
