---
# tasks file for installing wazuh backend on docker
- name: Create docker compose directory
  ansible.builtin.file:
    path: "{{ fabos_wazuh_backend_compose_dir | default(fabos_wazuh_default_backend_compose_dir) }}"
    state: directory
    mode: '0755'

- name: Download Wazuh docker-compose.yml
  ansible.builtin.get_url:
    url: "{{ fabos_wazuh_default_backend_compose_url | default(fabos_wazuh_default_backend_compose_url) }}"
    dest: "{{ fabos_wazuh_default_backend_compose_dir }}/"
    mode: '0644'
  register: downloaded_compose

- name: Start docker compose workload
  community.docker.docker_compose_v2:
    project_src: "{{ fabos_wazuh_default_backend_compose_dir }}"
    state: present
  register: docker_compose_result
