---
- name: Remove docker compose workloads
  community.docker.docker_compose_v2:
    project_src: "{{ fabos_wazuh_default_single_node_compose_dir }}"
    files: "{{ [item] }}"
    state: absent
  loop: "{{ fabos_wazuh_default_compose_files }}"

- name: Remove Wazuh Docker repository
  ansible.builtin.file:
    path: "{{ fabos_wazuh_default_wazuh_docker_dir }}"
    state: absent
